// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apps

import (
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"go-boilerplate/internal/configs"
	"go-boilerplate/internal/dbs"
	"go-boilerplate/internal/repositories"
	"go-boilerplate/internal/services"
	"go-boilerplate/internal/transports/http"
	"go-boilerplate/internal/transports/http/handlers"
	"go-boilerplate/internal/utils/logs"
	"go-boilerplate/internal/utils/validation"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeApp creates the complete application with all dependencies
func InitializeApp(cfg configs.Config) (*Application, func(), error) {
	db, err := dbs.NewMySQLDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := logs.ProvideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	validate := validation.GetValidator()
	exampleRepository := repositories.NewExampleRepository(db)
	exampleService := services.NewExampleService(exampleRepository, logger, cfg, validate)
	healthService := services.NewHealthService(cfg, logger, validate)
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository, cfg, logger, validate)
	exampleHandler := handlers.NewExampleHandler(exampleService)
	healthHandler := handlers.NewHealthHandler(healthService)
	userHandler := handlers.NewUserHandler(userService)
	server := http.NewHTTPServer(exampleHandler, healthHandler, userHandler, cfg)
	application := NewApplication(db, logger, validate, exampleService, healthService, userService, server)
	return application, func() {
		cleanup()
	}, nil
}

// InitializeHTTPApp creates application optimized for HTTP only
func InitializeHTTPApp(cfg configs.Config) (*http.Server, func(), error) {
	db, err := dbs.NewMySQLDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	exampleRepository := repositories.NewExampleRepository(db)
	logger, cleanup, err := logs.ProvideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	validate := validation.GetValidator()
	exampleService := services.NewExampleService(exampleRepository, logger, cfg, validate)
	exampleHandler := handlers.NewExampleHandler(exampleService)
	healthService := services.NewHealthService(cfg, logger, validate)
	healthHandler := handlers.NewHealthHandler(healthService)
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository, cfg, logger, validate)
	userHandler := handlers.NewUserHandler(userService)
	server := http.NewHTTPServer(exampleHandler, healthHandler, userHandler, cfg)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

var InfrastructureProviders = wire.NewSet(dbs.NewMySQLDB, logs.ProvideLogger, validation.GetValidator)

// Add your repositories here - they handle database operations
var RepositoryProviders = wire.NewSet(repositories.NewExampleRepository, repositories.NewUserRepository)

// Add your services here - they contain your business rules
var ServiceProviders = wire.NewSet(services.NewExampleService, services.NewHealthService, services.NewUserService)

// Add HTTP handlers here - they handle HTTP requests/responses
var HTTPHandlerProviders = wire.NewSet(handlers.NewExampleHandler, handlers.NewHealthHandler, handlers.NewUserHandler)

// These start the actual servers (HTTP, gRPC, etc.)
var ServerProviders = wire.NewSet(http.NewHTTPServer)

// Application represents the complete wired application
type Application struct {
	// Infrastructure
	DB        *sql.DB             // Database connection
	Logger    *zap.Logger         // Logger instance
	Validator *validator.Validate // Input validator

	// Services (Business Logic)
	ExampleService services.ExampleService
	HealthService  services.HealthService
	UserService    services.UserService

	// Transport Servers
	HTTPServer *http.Server
}

// NewApplication creates a new application with all dependencies wired
func NewApplication(

	db *sql.DB,
	logger *zap.Logger, validator2 *validator.Validate,

	exampleService services.ExampleService,
	healthService services.HealthService,
	userService services.UserService,

	httpServer *http.Server,
) *Application {
	return &Application{
		DB:             db,
		Logger:         logger,
		Validator:      validator2,
		ExampleService: exampleService,
		HealthService:  healthService,
		UserService:    userService,
		HTTPServer:     httpServer,
	}
}
