// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apps

import (
	"github.com/google/wire"
	"go-boilerplate/internal/configs"
	"go-boilerplate/internal/dbs"
	"go-boilerplate/internal/repositories"
	"go-boilerplate/internal/services"
	"go-boilerplate/internal/transports/http"
	"go-boilerplate/internal/transports/http/handlers"
	"go-boilerplate/internal/utils/validation"
)

// Injectors from wire.go:

// InitializeApp creates the application with all dependencies
func InitializeApp(cfg configs.Config) (*Application, func(), error) {
	validate := validation.GetValidator()
	healthService := services.NewHealthService(cfg, validate)
	healthHandler := handlers.NewHealthHandler(healthService)
	db, cleanup, err := dbs.NewMySQLDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository, cfg, validate)
	userHandler := handlers.NewUserHandler(userService)
	server := http.NewHTTPServer(healthHandler, userHandler, cfg)
	application := NewApplication(server)
	return application, func() {
		cleanup()
	}, nil
}

// wire.go:

var InfrastructureProviders = wire.NewSet(dbs.NewMySQLDB, validation.GetValidator)

var RepositoryProviders = wire.NewSet(repositories.NewUserRepository)

var ServiceProviders = wire.NewSet(services.NewHealthService, services.NewUserService)

var HandlerProviders = wire.NewSet(handlers.NewHealthHandler, handlers.NewUserHandler)

var TransportProvider = http.NewHTTPServer

// Application holds the main application server
type Application struct {
	Server *http.Server // Change type when switching transport
}

// NewApplication creates a new Application
func NewApplication(
	server *http.Server,
) *Application {
	return &Application{
		Server: server,
	}
}
